name: legendaries
version: '${version}'
main: org.olavorw.legendaries.Legendaries
api-version: '1.21'
commands:
  irondagger:
    description: Give yourself or another player the Deathripper Dagger item.
    usage: /irondagger [player]
    permission: legendaries.irondagger
permissions:
  legendaries.irondagger:
    description: Allows use of /irondagger
    default: op
